apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - base/postgres.yaml
  - base/redis.yaml
  - apps/api-deployment.yaml
  - apps/api-service.yaml
  - apps/admin.yaml
  - apps/portal.yaml
